project:
  type: website
  output-dir: docs

website:  
  title: "Homepage"
  navbar:
    search: false
    left:
      - text: "Residential Seggregation"
        file: index.qmd
      - text: "Exploration"
        file: site_visit.qmd
      - text: "Minneapolis' Current Environmental Status"
        file: msp_enviro_injustice.qmd
      - text: "Why Urban Green Spaces"
        file: urban_green_spaces.qmd

format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true
    theme:
      - custom.css

